# Test
sudo: required
dist: trusty
branches:
  except:
    - trunk
language: c++
compiler:
  - gcc
#  - clang
before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo apt-get build-dep -qq gnucash
  - sudo apt-get install -qq swig
  - sudo apt-get install -qq libboost-all-dev libgtk-3-dev libwebkit2gtk-3.0-dev
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
  - git clone https://github.com/google/googletest -b release-1.8.0 ~/gtest

##  - sudo dpkg-query -l '*cmake*'
##  - sudo apt-get install -qq cmake
##  - sudo dpkg-query -l '*cmake*'
##  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) updatesbogus"
##  - sudo apt-get update -qq
  - sudo dpkg-query -l '*cmake*'
  - sudo apt-get install -qq cmake3
  - sudo dpkg-query -l '*cmake*'

#script: ./autogen.sh && ./configure --enable-python GTEST_ROOT=~/gtest/googletest GMOCK_ROOT=~/gtest/googlemock && make && TZ="America/Los_Angeles" make check
script: 'mkdir ~/build/build && cd ~/build/build && cmake -DWITH_PYTHON=true -DGTEST_ROOT=~/gtest/googletest -DGMOCK_ROOT=~/gtest/googlemock "$TRAVIS_BUILD_DIR" && make && TZ="America/Los_Angeles" make check'
